# -----------------------------------------------------------------------------------------------------
# This file holds database-related information.
#
# **IMPORTANT** The utf8mb4_unicode_520_ci collation (database encoding) is required, because we need
# need to store messages in 4 bytes (mb4) due to unicode/emojis/non-English letter support.

#
# This file does NOT support reloading.
# -----------------------------------------------------------------------------------------------------

# Available: local (just works, no configuration needed, uses SQLite)
#            remote (requires Host, Database, User, Password set below, supports MySQL/MariaDB)
Type: 'local'

# The remote database connection settings. Only configure if using remote database.
Host: 'localhost:3306'
Database: ''
User: ''
Password: ''

# Customize the connection string
Line: "jdbc:{driver}://{host}/{database}?autoReconnect=true&characterEncoding=UTF-8&tcpKeepAlive=true&useSSL=false"